language: objective-c

os:
  - osx 

compiler: 
  - clang

before_install:
  - brew update
  - brew install libffi
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
