Import('env', 'install_dir')

common_source = Split("""
  filein.c
  interp.c
  lex.c
  memory.c
  names.c
  parser.c
  primitive.c
  sysprimitive.c
  unixio.c
""")

env.Append(LIBS = env['TW_LIBS'])

main_env = env.Clone();
main_env.VariantDir('main', '.')
main_env.Append(CPPDEFINES = ['TW_NO_COMPILER'])

tw_source = [ 'main/st.c' ]
initial_source = [ 'initial.c' ]

tw_source += [ 'main/%s' % x for x in common_source ] 
tw = main_env.Program('tw', tw_source)
initial = env.Program('initial', common_source + initial_source)

main_env.Install(install_dir, tw)

Export('initial')

# ex: set filetype=python tabstop=2 shiftwidth=2 expandtab: 
